eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:9861/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
