spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    test-on-borrow: true
    test-while-idle: true
    validation-query: SELECT 1
    time-between-eviction-runs-millis: 5000
    min-evictable-idle-time-millis: 60000

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:9861/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  #  eager-load:
  #    enabled: true
  ReadTimeout: 30000
  ConnectTimeout: 30000
  #最大连接数
  MaxTotalConnections: 500
  #每个host的最大连接数
  MaxConnectionsPerHost: 500
  #负载均衡器操作接口
  NFLoadBalancerClassName: com.netflix.loadbalancer.ZoneAwareLoadBalancer
  #负载均衡策略
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.AvailabilityFilteringRule
  #服务可用性检查策略
  NFLoadBalancerPingClassName: com.netflix.loadbalancer.DummyPing
  #服务列表获取
  NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

data:
  address: test1
  user:
    username: name
    password: password
