server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_test?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    test-on-borrow: true
    test-while-idle: true
    validation-query: SELECT 1
    time-between-eviction-runs-millis: 5000
    min-evictable-idle-time-millis: 60000

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:9861/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
